version: 2.1

orbs:
  python: circleci/python@1.2.1

jobs:
  build:
    executor: python/default
    steps:
      - checkout
      - python/install-packages:
          pip-dependency-file: requirements.txt
          pkg-manager: pip

workflows:
  main:
    jobs:
      - build
      - python/test:
          pkg-manager: pip
          test-tool: pytest
