name: sam2nyx_unet_256
new: true
location: model_instances
generator:
  filters:
    - 32
    - 32
    - 64
    - 64
  kernels:
    - 3
    - 3
    - 3
    - 3
  expansion: transpose
  normalization: instance
discriminator:
  filters:
    - 32
    - 32
    - 32
  kernels:
    - 7
    - 5
    - 3
  expansion: transpose
  normalization: instance
loss_weights:
  cycle: 4
  identity: 1
  generator: 1
  discriminator: 1
