name: cat2scrunge
new: true
location: model_instances
generator:
  type: resnet_generator
  filters:
    - 32
    - 32
    - 64
    - 64
  kernels:
    - 4
    - 4
    - 4
    - 4
  output_channels: 3
  expansion: upsample
  normalization: instancenorm
  dropout: False
  final_activation: tanh
discriminator:
  type: unet_generator
  filters:
    - 32
    - 32
    - 32
  kernels:
    - 7
    - 5
    - 3
  output_channels: 1
  expansion: upsample
  normalization: instancenorm
  dropout: False
  final_activation: sigmoid
loss_weights:
  cycle: 2.0
  identity: 0.5
  generator: 0.5
  discriminator: 1.0
