epochs: 100
batch_size: 4
image_size: 128
g_opt:
  name: adam
  learning_rate: 0.0001
  beta_1: 0.5
d_opt:
  name: adam
  learning_rate: 0.001
  beta_1: 0.5
summary:
  samples: 8
  images: 5
  model: 20

